#!/bin/bash
rm -rf mergedfiles_sorted.txt
awk -F '/' '{print $2}' ../../ucfTrainTestlist/testlist01.txt > mergedfiles1.txt
cat -n mergedfiles1.txt > mergedfiles2.txt
paste mergedfiles1.txt mergedfiles2.txt > mergedfiles.txt
ls ../JMMV/JMMV_Test01_QP51_MVSR16_MVRes8_Opt1a/ > list_file.txt
awk -F '_' '{print $2"_"$3"_"$4"_"$5}' ./list_file.txt >> mergedfiles.txt
sort -k 1,1 -s mergedfiles.txt > mergedfiles_sorted.txt
rm -rf mergedfiles1.txt
rm -rf mergedfiles2.txt
rm -rf mergedfiles.txt
rm -rf list_file.txt
rm -rf mergedfiles.txt
 

