#!/bin/bash
clear
cd JM_MVX_NoTexture
make
cd bin
rm mv.bin
./lencod.exe -f encoder_CO.cfg -p InputFile="./vid/box.yuv" -p OutputFile="./vid/Boxing_NoTexture.264"
./ldecod.exe -f decoder_CO.cfg -p InputFile="./vid/Boxing_NoTexture.264" -p OutputFile="./vid/Boxing_decoded.yuv"
rm ../../mbmap/mv.bin
cp mv.bin ../../mbmap/
cd ../../mbmap
rm jmmv.bin
./mbmap -h 240 -w 320 -o jmmv_NoText.bin mv.bin
cp ./jmmv_NoText.bin ../../../UCLResearch/MVX/
cd ..


cd JM_MVX
make
cd bin
rm mv.bin
./lencod.exe -f encoder_CO.cfg -p InputFile="./vid/box.yuv" -p OutputFile="./vid/Boxing_NoTexture.264"
./ldecod.exe -f decoder_CO.cfg -p InputFile="./vid/Boxing_NoTexture.264" -p OutputFile="./vid/Boxing_decoded.yuv"
rm ../../mbmap/mv.bin
cp mv.bin ../../mbmap/
cd ../../mbmap
rm jmmv.bin
./mbmap -h 240 -w 320 -o jmmv.bin mv.bin
cp ./jmmv.bin ../../../UCLResearch/MVX/
