#!/bin/bash
clear

#%%%%%%%%%% deleting .264 videos from previous run
rm ./JM_MVX_NoTexture/bin/vid/Boxing_NoTexture.264
rm ./JM_MVX/bin/vid/Boxing.264
rm ./JM_MVX/bin/vid/Boxing_ffmpeg_Option3.264
rm ./JM_MVX/bin/vid/Boxing_ffmpeg_Option4.264
rm ./JM_MVX/bin/vid/Boxing_ffmpeg_Option5.264

#%%%%%%%%%% deleting estracted MVs from previous run
rm ./mbmap/mv_Option1.bin
rm ./mbmap/mv_Option2.bin
rm ./mbmap/mv_Option3.bin
rm ./mbmap/mv_Option4.bin
rm ./mbmap/mv_Option5.bin

#%%%%%%%%%% encode and decode using Original JM to encode and decode (from yuv to 264)
cd ./JM_MVX/bin
rm mv.bin
./lencod.exe -f encoder_CO_ToCompare.cfg -p InputFile="./vid/box.yuv" -p OutputFile="./vid/Boxing.264"
./ldecod.exe -f decoder_CO.cfg -p InputFile="./vid/Boxing.264" -p OutputFile="./vid/Boxing_decoded.yuv"
mv mv.bin ../../mbmap/mv_Option1.bin

#%%%%%%%%%% encode and decode using modified JM to encode and decode (from yuv to 264)
cd ../../JM_MVX_NoTexture/bin
rm mv.bin
cp ../../JM_MVX/bin/encoder_CO.cfg .
./lencod.exe -f encoder_CO.cfg -p InputFile="./vid/box.yuv" -p OutputFile="./vid/Boxing_NoTexture.264"
./ldecod.exe -f decoder_CO.cfg -p InputFile="./vid/Boxing_NoTexture.264" -p OutputFile="./vid/Boxing_decoded.yuv"
mv mv.bin ../../mbmap/mv_Option2.bin

#%%%%%%%%%% encoding the yuv videos using ffmpeg
cd ../../JM_MVX/bin/vid

ffmpeg -y -i box.avi -c:v libx264 -b:v 1M -bf 0 -r 25  Boxing_ffmpeg_Option3.264

ffmpeg -f rawvideo -pix_fmt yuv420p -s:v 320x240 -r 25 -i box.yuv -c:v libx264 -coder 0 -refs 3 -me_method hex -subq 7 -me_range 16 -trellis 1 -8x8dct 1 -bf 0 -weightp 2 -g 250 -keyint_min 25 -sc_threshold 40 -rc_lookahead 40 -rc abr -mbtree 1 -b 1M -bt 1.0 -qcomp 0.60 -qmin 0 -qmax 69 -qdiff 4 Boxing_ffmpeg_Option4.264

ffmpeg -f rawvideo -pix_fmt yuv420p -s:v 320x240 -r 25 -i box.yuv -c:v libx264 -coder 1 -refs 3 -me_method hex -subq 7 -me_range 16 -trellis 1 -8x8dct 1 -bf 0 -weightp 2 -g 250 -keyint_min 25 -sc_threshold 40 -rc_lookahead 40 -rc abr -mbtree 1 -b 1M -bt 1.0 -qcomp 0.60 -qmin 0 -qmax 69 -qdiff 4 Boxing_ffmpeg_Option5.264

#ffmpeg -f rawvideo -pix_fmt yuv420p -s:v 320x240 -r 25 -i box.yuv -c:v libx264 -qp 28 -coder 0 -bf 0 -r 25 Boxing_ffmpeg_Option3.264
#ffmpeg -f rawvideo -pix_fmt yuv420p -s:v 320x240 -r 25 -i box.yuv -c:v libx264 -qp 30 -coder 0 -bf 0 -r 25 Boxing_ffmpeg_Option4.264
#ffmpeg -f rawvideo -pix_fmt yuv420p -s:v 320x240 -r 25 -i box.yuv -c:v libx264 -qp 32 -coder 0 -bf 0 -r 25 Boxing_ffmpeg_Option5.264

#%%%%%%%%%% decoding the ffmpeg encoded .264 files using JM
cd ..
./ldecod.exe -f decoder_CO.cfg -p InputFile="./vid/Boxing_ffmpeg_Option3.264" -p OutputFile="./vid/Boxing_decoded.yuv"
mv mv.bin ../../mbmap/mv_Option3.bin

./ldecod.exe -f decoder_CO.cfg -p InputFile="./vid/Boxing_ffmpeg_Option4.264" -p OutputFile="./vid/Boxing_decoded.yuv"
mv mv.bin ../../mbmap/mv_Option4.bin

./ldecod.exe -f decoder_CO.cfg -p InputFile="./vid/Boxing_ffmpeg_Option5.264" -p OutputFile="./vid/Boxing_decoded.yuv"
mv mv.bin ../../mbmap/mv_Option5.bin

#%%%%%%%%%% deleteing old processed MV files
cd ../../mbmap
rm jmmv_ffmpeg_Option1.bin
rm jmmv_ffmpeg_Option2.bin
rm jmmv_ffmpeg_Option3.bin
rm jmmv_ffmpeg_Option4.bin
rm jmmv_ffmpeg_Option5.bin

#%%%%%%%%%% Extracting the MVs
./mbmap -h 240 -w 320 -o jmmv_ffmpeg_Option1.bin mv_Option1.bin
./mbmap -h 240 -w 320 -o jmmv_ffmpeg_Option2.bin mv_Option2.bin
./mbmap -h 240 -w 320 -o jmmv_ffmpeg_Option3.bin mv_Option3.bin
./mbmap -h 240 -w 320 -o jmmv_ffmpeg_Option4.bin mv_Option4.bin
./mbmap -h 240 -w 320 -o jmmv_ffmpeg_Option5.bin mv_Option5.bin


#%%%%%%%%%% copying the MVs to the directory to be processed by matlab
mv ./jmmv_ffmpeg_Option1.bin ../../../UCLResearch/MVX/
mv ./jmmv_ffmpeg_Option2.bin ../../../UCLResearch/MVX/
mv ./jmmv_ffmpeg_Option3.bin ../../../UCLResearch/MVX/
mv ./jmmv_ffmpeg_Option4.bin ../../../UCLResearch/MVX/
mv ./jmmv_ffmpeg_Option5.bin ../../../UCLResearch/MVX/
