#!/bin/bash
clear


R=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP0_MVSR16_MVRes8_A/JMMV_HMDB_Train01_QP0_MVSR16_MVRes8_A
echo $R
sleep 10
#rm -rf $R'_Conv'
#python ./convert_HMDB_bin.py --data_dir=$R --out_dir=$R'_Conv' --path_to_file_list=./HMDB_trainlist01.txt --prefix=JMMV_
cd $R'_Conv'
#find . -name '*.bin' -exec bash -c ' mv $0 ${0/\JMMV/rgb24}' {} \;
ls -la
cd /data0/Mohd_ALL_JM_MV_CNN/JM_MV_CNN_Options/JM_MV_CNN
sleep 10

R=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP0_MVSR16_MVRes8_A/JMMV_HMDB_Test01_QP0_MVSR16_MVRes8_A
echo $R
sleep 10
#rm -rf $R'_Conv'
#python ./convert_HMDB_bin.py --data_dir=$R --out_dir=$R'_Conv' --path_to_file_list=./HMDB_testlist01.txt --prefix=JMMV_
cd $R'_Conv'
#find . -name '*.bin' -exec bash -c ' mv $0 ${0/\JMMV/rgb24}' {} \;
ls -la
cd /data0/Mohd_ALL_JM_MV_CNN/JM_MV_CNN_Options/JM_MV_CNN
sleep 10


R=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP0_MVSR16_MVRes8_A16/JMMV_HMDB_Test01_QP0_MVSR16_MVRes8_A16
echo $R
sleep 10
#rm -rf $R'_Conv'
#python ./convert_HMDB_bin.py --data_dir=$R --out_dir=$R'_Conv' --path_to_file_list=./HMDB_testlist01_Short.txt --prefix=JMMV_ 
cd $R'_Conv'
#find . -name '*.bin' -exec bash -c ' mv $0 ${0/\JMMV/rgb24}' {} \;
ls -la
cd /data0/Mohd_ALL_JM_MV_CNN/JM_MV_CNN_Options/JM_MV_CNN
sleep 10


R=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP0_MVSR16_MVRes8_A16/JMMV_HMDB_Train01_QP0_MVSR16_MVRes8_A16
echo $R
sleep 10
#rm -rf $R'_Conv'
#python ./convert_HMDB_bin.py --data_dir=$R --out_dir=$R'_Conv' --path_to_file_list=./HMDB_trainlist01_Short.txt --prefix=JMMV_
cd $R'_Conv' 
#find . -name '*.bin' -exec bash -c ' mv $0 ${0/\JMMV/rgb24}' {} \;
ls -la
cd /data0/Mohd_ALL_JM_MV_CNN/JM_MV_CNN_Options/JM_MV_CNN
sleep 10


R=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP30_MVSR16_MVRes8_A/JMMV_HMDB_Train01_QP30_MVSR16_MVRes8_A
echo $R
sleep 10
#rm -rf $R'_Conv'
#python ./convert_HMDB_bin.py --data_dir=$R --out_dir=$R'_Conv' --path_to_file_list=./HMDB_trainlist01.txt --prefix=JMMV_
cd $R'_Conv'
#find . -name '*.bin' -exec bash -c ' mv $0 ${0/\JMMV/rgb24}' {} \;
ls -la
cd /data0/Mohd_ALL_JM_MV_CNN/JM_MV_CNN_Options/JM_MV_CNN
sleep 10


R=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP30_MVSR16_MVRes8_A/JMMV_HMDB_Test01_QP30_MVSR16_MVRes8_A
echo $R
sleep 10
#rm -rf $R'_Conv'
#python ./convert_HMDB_bin.py --data_dir=$R --out_dir=$R'_Conv' --path_to_file_list=./HMDB_testlist01.txt --prefix=JMMV_
cd $R'_Conv'
#find . -name '*.bin' -exec bash -c ' mv $0 ${0/\JMMV/rgb24}' {} \;
ls -la
cd /data0/Mohd_ALL_JM_MV_CNN/JM_MV_CNN_Options/JM_MV_CNN
sleep 10


R=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP30_MVSR16_MVRes8_A16/JMMV_HMDB_Test01_QP30_MVSR16_MVRes8_A16
echo $R
sleep 10
#rm -rf $R'_Conv'
#python ./convert_HMDB_bin.py --data_dir=$R --out_dir=$R'_Conv' --path_to_file_list=./HMDB_testlist01.txt --prefix=JMMV_
cd $R'_Conv'
#find . -name '*.bin' -exec bash -c ' mv $0 ${0/\JMMV/rgb24}' {} \;
ls -la
cd /data0/Mohd_ALL_JM_MV_CNN/JM_MV_CNN_Options/JM_MV_CNN
sleep 10


R=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP30_MVSR16_MVRes8_A16/JMMV_HMDB_Train01_QP30_MVSR16_MVRes8_A16
echo $R
sleep 10
#rm -rf $R'_Conv'
#python ./convert_HMDB_bin.py --data_dir=$R --out_dir=$R'_Conv' --path_to_file_list=./HMDB_trainlist01.txt --prefix=JMMV_
cd $R'_Conv'
#find . -name '*.bin' -exec bash -c ' mv $0 ${0/\JMMV/rgb24}' {} \;
ls -la
cd /data0/Mohd_ALL_JM_MV_CNN/JM_MV_CNN_Options/JM_MV_CNN
sleep 10


R=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP40_MVSR16_MVRes8_A16/JMMV_HMDB_Train01_QP40_MVSR16_MVRes8_A16
echo $R
sleep 10
#rm -rf $R'_Conv'
#python ./convert_HMDB_bin.py --data_dir=$R --out_dir=$R'_Conv' --path_to_file_list=./HMDB_trainlist01.txt --prefix=JMMV_
cd $R'_Conv'
#find . -name '*.bin' -exec bash -c ' mv $0 ${0/\JMMV/rgb24}' {} \;
ls -la
cd /data0/Mohd_ALL_JM_MV_CNN/JM_MV_CNN_Options/JM_MV_CNN
sleep 10


R=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP40_MVSR16_MVRes8_A16/JMMV_HMDB_Test01_QP40_MVSR16_MVRes8_A16
echo $R
sleep 10
#rm -rf $R'_Conv'
#python ./convert_HMDB_bin.py --data_dir=$R --out_dir=$R'_Conv' --path_to_file_list=./HMDB_testlist01.txt --prefix=JMMV_
cd $R'_Conv'
#find . -name '*.bin' -exec bash -c ' mv $0 ${0/\JMMV/rgb24}' {} \;
ls -la
cd /data0/Mohd_ALL_JM_MV_CNN/JM_MV_CNN_Options/JM_MV_CNN
sleep 10


R=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP51_MVSR16_MVRes8_A/JMMV_HMDB_Test01_QP51_MVSR16_MVRes8_A
echo $R
sleep 10
#rm -rf $R'_Conv'
#python ./convert_HMDB_bin.py --data_dir=$R --out_dir=$R'_Conv' --path_to_file_list=./HMDB_testlist01.txt --prefix=JMMV_
cd $R'_Conv'
#find . -name '*.bin' -exec bash -c ' mv $0 ${0/\JMMV/rgb24}' {} \;
ls -la
cd /data0/Mohd_ALL_JM_MV_CNN/JM_MV_CNN_Options/JM_MV_CNN
sleep 10


R=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP51_MVSR16_MVRes8_A/JMMV_HMDB_Train01_QP51_MVSR16_MVRes8_A
echo $R
sleep 10
#rm -rf $R'_Conv'
#python ./convert_HMDB_bin.py --data_dir=$R --out_dir=$R'_Conv' --path_to_file_list=./HMDB_trainlist01.txt --prefix=JMMV_
cd $R'_Conv'
#find . -name '*.bin' -exec bash -c ' mv $0 ${0/\JMMV/rgb24}' {} \;
ls -la
cd /data0/Mohd_ALL_JM_MV_CNN/JM_MV_CNN_Options/JM_MV_CNN
sleep 10


R=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP51_MVSR16_MVRes8_A16/JMMV_HMDB_Train01_QP51_MVSR16_MVRes8_A16
echo $R
sleep 10
#rm -rf $R'_Conv'
#python ./convert_HMDB_bin.py --data_dir=$R --out_dir=$R'_Conv' --path_to_file_list=./HMDB_trainlist01.txt --prefix=JMMV_
cd $R'_Conv'
#find . -name '*.bin' -exec bash -c ' mv $0 ${0/\JMMV/rgb24}' {} \;
ls -la
cd /data0/Mohd_ALL_JM_MV_CNN/JM_MV_CNN_Options/JM_MV_CNN
sleep 10


R=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP51_MVSR16_MVRes8_A16/JMMV_HMDB_Test01_QP51_MVSR16_MVRes8_A16
echo $R
sleep 10
#rm -rf $R'_Conv'
#python ./convert_HMDB_bin.py --data_dir=$R --out_dir=$R'_Conv' --path_to_file_list=./HMDB_testlist01.txt --prefix=JMMV_
cd $R'_Conv'
#find . -name '*.bin' -exec bash -c ' mv $0 ${0/\JMMV/rgb24}' {} \;
ls -la
cd /data0/Mohd_ALL_JM_MV_CNN/JM_MV_CNN_Options/JM_MV_CNN
sleep 10
