#!/bin/bash
clear


P=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP0_MVSR16_MVRes8_A/JMMV_HMDB_Train01_QP0_MVSR16_MVRes8_A
echo $p
python ./convert_HMDB_bin.py --data_dir=$P --out_dir=$P'_Conv' --path_to_file_list=./HMDB_trainlist01.txt --prefix=JMMV_

P=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP0_MVSR16_MVRes8_A/JMMV_HMDB_Test01_QP0_MVSR16_MVRes8_A
echo $p
python ./convert_HMDB_bin.py --data_dir=$P --out_dir=$P'_Conv' --path_to_file_list=./HMDB_testlist01.txt --prefix=JMMV_




p=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP0_MVSR16_MVRes8_A16/JMMV_HMDB_Test01_QP0_MVSR16_MVRes8_A16
echo $p
python ./convert_HMDB_bin.py --data_dir=$P --out_dir=$P'_Conv' --path_to_file_list=./HMDB_testlist01_Short.txt --prefix=JMMV_

p=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP0_MVSR16_MVRes8_A16/JMMV_HMDB_Train01_QP0_MVSR16_MVRes8_A16
echo $p
python ./convert_HMDB_bin.py --data_dir=$P --out_dir=$P'_Conv' --path_to_file_list=./HMDB_trainlist01_Short.txt --prefix=JMMV_




p=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP30_MVSR16_MVRes8_A/JMMV_HMDB_Train01_QP30_MVSR16_MVRes8_A
echo $p
python ./convert_HMDB_bin.py --data_dir=$P --out_dir=$P'_Conv' --path_to_file_list=./HMDB_trainlist01.txt --prefix=JMMV_

p=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP30_MVSR16_MVRes8_A/JMMV_HMDB_Test01_QP30_MVSR16_MVRes8_A
echo $p
python ./convert_HMDB_bin.py --data_dir=$P --out_dir=$P'_Conv' --path_to_file_list=./HMDB_testlist01.txt --prefix=JMMV_




p=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP30_MVSR16_MVRes8_A16/JMMV_HMDB_Test01_QP30_MVSR16_MVRes8_A16
echo $p
python ./convert_HMDB_bin.py --data_dir=$P --out_dir=$P'_Conv' --path_to_file_list=./HMDB_testlist01.txt --prefix=JMMV_

p=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP30_MVSR16_MVRes8_A16/JMMV_HMDB_Train01_QP30_MVSR16_MVRes8_A16
echo $p
python ./convert_HMDB_bin.py --data_dir=$P --out_dir=$P'_Conv' --path_to_file_list=./HMDB_trainlist01.txt --prefix=JMMV_





p=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP40_MVSR16_MVRes8_A16/JMMV_HMDB_Train01_QP40_MVSR16_MVRes8_A16
echo $p
python ./convert_HMDB_bin.py --data_dir=$P --out_dir=$P'_Conv' --path_to_file_list=./HMDB_trainlist01.txt --prefix=JMMV_

p=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP40_MVSR16_MVRes8_A16/JMMV_HMDB_Test01_QP40_MVSR16_MVRes8_A16
echo $p
python ./convert_HMDB_bin.py --data_dir=$P --out_dir=$P'_Conv' --path_to_file_list=./HMDB_testlist01.txt --prefix=JMMV_




p=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP51_MVSR16_MVRes8_A/JMMV_HMDB_Test01_QP51_MVSR16_MVRes8_A
echo $p
python ./convert_HMDB_bin.py --data_dir=$P --out_dir=$P'_Conv' --path_to_file_list=./HMDB_testlist01.txt --prefix=JMMV_

p=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP51_MVSR16_MVRes8_A/JMMV_HMDB_Train01_QP51_MVSR16_MVRes8_A
echo $p
python ./convert_HMDB_bin.py --data_dir=$P --out_dir=$P'_Conv' --path_to_file_list=./HMDB_trainlist01.txt --prefix=JMMV_




p=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP51_MVSR16_MVRes8_A16/JMMV_HMDB_Train01_QP51_MVSR16_MVRes8_A16
echo $p
python ./convert_HMDB_bin.py --data_dir=$P --out_dir=$P'_Conv' --path_to_file_list=./HMDB_trainlist01.txt --prefix=JMMV_

p=/data0/Mohd_ALL_JM_MV_CNN/JMMV_Options/JM_HMDB_QP51_MVSR16_MVRes8_A16/JMMV_HMDB_Test01_QP51_MVSR16_MVRes8_A16
echo $p
python ./convert_HMDB_bin.py --data_dir=$P --out_dir=$P'_Conv' --path_to_file_list=./HMDB_testlist01.txt --prefix=JMMV_
