#!/bin/bash
clear
cd ..

#%%% Must edit
enc_cfg=encoder_option2.cfg	#JM encoder configuration file
QPISlice=35 			#value [0 - 51]
QPPSlice=35 			#value [0 - 51]
SearchRange=16			#value [16,32,64]
mbmapXxX=4			#value [8,16]
SetType="train"			#value [0:Train Set,1: Test Set]
TTSet=01			#UCF-101 Split Set [01 02 03]
IndexFirstVideo=1		#Index of first video to be encoded [1,2, .... ]
NumVideos=10000			#Number of Video files to be encoded
Overwrite=1			#Overwrite any exisitng MV files in the directory
StrComment="Opt2b"		#Comment to be added at the end of the directory that will be made (if doesn't exist) to contain the output MVs
#%%%%%
N=9; 				#Number of Parallel Processes 
#%%%%

cnt=$IndexFirstVideo;
Inc=$((NumVideos/N));
Inc2=$((NumVideos%N));
if [ $Inc2 -gt 0 ];
then
echo "Number of Videos % Number of Multiple Processes != 0"
fi

i=1;
while [ $i -le $N ]
do 
cp -R JM_MV_CNN/ JM_MV_CNN$i &
i=$((i+1));
done
wait

i=1
while [ $i -le $N ]
do
if [ $i -eq $N ]
then
Inc=$((NumVideos + IndexFirstVideo - cnt));
fi
cd ./JM_MV_CNN$i
./Generate-Split-1 -ecfg=$enc_cfg -qp=$QPISlice -sr=$SearchRange -res=$mbmapXxX -settype=$SetType -sset=$TTSet -ifvid=$cnt -nvid=$Inc -ow=$Overwrite -strcom=$StrComment &
cnt=$((cnt+Inc));
i=$((i+1));
cd ..
done
wait

i=1;
while [ $i -le $N ]
do
rm -rf JM_MV_CNN$i &
i=$((i+1));
done
wait
