#!/bin/bash
clear

#%%%%%%%%%% deleting .264 videos from previous run
rm ./JM_MVX_NoTexture/bin/vid/Boxing_NoTexture.264

#%%%%%%%%%% deleting estracted MVs from previous run
rm ./mbmap/mv_Option1.bin

#%%%%%%%%%% encode and decode using Original JM to encode and decode (from yuv to 264)
cd ./JM_MVX/bin
rm mv.bin
./lencod.exe -f encoder_CO_ToCompare.cfg -p InputFile="./vid/box.yuv" -p OutputFile="./vid/Boxing.264"
./ldecod.exe -f decoder_CO.cfg -p InputFile="./vid/Boxing.264" -p OutputFile="./vid/Boxing_decoded.yuv"
mv mv.bin ../../mbmap/mv_Option1.bin

#%%%%%%%%%% encode and decode using modified JM to encode and decode (from yuv to 264)
cd ../../JM_MVX_NoTexture/bin
rm mv.bin
cp ../../JM_MVX/bin/encoder_CO.cfg .
./lencod.exe -f encoder_CO.cfg -p InputFile="./vid/box.yuv" -p OutputFile="./vid/Boxing_NoTexture.264"
./ldecod.exe -f decoder_CO.cfg -p InputFile="./vid/Boxing_NoTexture.264" -p OutputFile="./vid/Boxing_decoded.yuv"
mv mv.bin ../../mbmap/mv_Option2.bin


#%%%%%%%%%% deleteing old processed MV files
cd ../../mbmap
rm jmmv_ffmpeg_Option1.bin


#%%%%%%%%%% Extracting the MVs
./mbmap -h 240 -w 320 -o jmmv_ffmpeg_Option1.bin mv_Option1.bin


#%%%%%%%%%% copying the MVs to the directory to be processed by matlab
mv ./jmmv_ffmpeg_Option1.bin ../../../UCLResearch/MVX/
