#!/bin/bash
clear

QP_List='0'
MVSR_List='16'
SpatialInterPolation_List='1'
MVResolution_List='4'
InputFile="box.yuv"

for MVResolution in $MVResolution_List
do
 for SpatialInterPolation in $SpatialInterPolation_List
 do 
  for MVSR in $MVSR_List
  do
   for QP in $QP_List
   do
    echo QP=$QP , Search Range=$MVSR, Spatial Interpolation=$SpatialInterPolation, MV Resolution=$MVResolution
    ./TryMe_JM_Function $QP $MVSR  $SpatialInterPolation $MVResolution $InputFile
   done
  done
 done
done
