#!/bin/bash
clear

cd JM_MVX
cd bin
rm mv.bin
cd vid
#%%%%%%%%%% deleting .264 videos from previous run
rm Boxing_ffmpeg_Option1.264 
rm Boxing_ffmpeg_Option2.264
rm Boxing_ffmpeg_Option3.264
rm Boxing_ffmpeg_Option4.264
rm Boxing_ffmpeg_Option5.264

#%%%%%%%%%% encoding the yuv videos
#ffmpeg -y -i box.avi -c:v libx264 -b:v 1M -bf 0 -r 25  Boxing_ffmpeg_Option1.264

#ffmpeg -f rawvideo -pix_fmt yuv420p -s:v 320x240 -r 25 -i box.yuv -c:v libx264 -coder 1 -refs 3 -me_method hex -subq 7 -me_range 16 -trellis 1 -8x8dct 1 -bf 0 -weightp 2 -g 250 -keyint_min 25 -sc_threshold 40 -rc_lookahead 40 -rc abr -mbtree 1 -b 1M -bt 1.0 -qcomp 0.60 -qmin 0 -qmax 69 -qdiff 4 Boxing_ffmpeg_Option2.264

#ffmpeg -f rawvideo -pix_fmt yuv420p -s:v 320x240 -r 25 -i box.yuv -c:v libx264 -coder 0 -refs 3 -me_method hex -subq 7 -flags2 +mixed_refs 1 -me_range 16 -trellis 1 -8x8dct 1 -flags2 -fastpskip 1 -bf 0 -weightp 2 -g 250 -keyint_min 25 -sc_threshold 40 -rc_lookahead 40 -rc abr -mbtree 1 -b 1000 -bt 1.0 -qcomp 0.60 -qmin 0 -qmax 69 -qdiff 4 Boxing_ffmpeg_Option2.264

ffmpeg -f rawvideo -pix_fmt yuv420p -s:v 320x240 -r 25 -i box.yuv -c:v libx264 -qp 0 -coder 0 -bf 0 -r 25 Boxing_ffmpeg_Option1.264
ffmpeg -f rawvideo -pix_fmt yuv420p -s:v 320x240 -r 25 -i box.yuv -c:v libx264 -qp 36 -coder 0 -bf 0 -r 25 Boxing_ffmpeg_Option2.264
ffmpeg -f rawvideo -pix_fmt yuv420p -s:v 320x240 -r 25 -i box.yuv -c:v libx264 -qp 40 -coder 0 -bf 0 -r 25 Boxing_ffmpeg_Option3.264
ffmpeg -f rawvideo -pix_fmt yuv420p -s:v 320x240 -r 25 -i box.yuv -c:v libx264 -qp 44 -coder 0 -bf 0 -r 25 Boxing_ffmpeg_Option4.264
ffmpeg -f rawvideo -pix_fmt yuv420p -s:v 320x240 -r 25 -i box.yuv -c:v libx264 -qp 51 -coder 0 -bf 0 -r 25 Boxing_ffmpeg_Option5.264


#ffmpeg -y -i box.avi -c:v libx264 -qp 23 -coder 0 -bf 0 -r 25 Boxing_ffmpeg_Option1.264
#ffmpeg -y -i box.avi -c:v libx264 -qp 23 -coder 0 -bf 0 -r 25 Boxing_ffmpeg_Option2.264
#ffmpeg -y -i box.avi -c:v libx264 -qp 23 -coder 0 -bf 0 -r 25 Boxing_ffmpeg_Option3.264
#ffmpeg -y -i box.avi -c:v libx264 -qp 23 -coder 0 -bf 0 -r 25 Boxing_ffmpeg_Option4.264
#ffmpeg -y -i box.avi -c:v libx264 -qp 23 -coder 0 -bf 0 -r 25 Boxing_ffmpeg_Option5.264

#%%%%%%%%%% deleting estracted MVs from previous run
cd ..
rm ../../mbmap/mv_Option1.bin
rm ../../mbmap/mv_Option2.bin
rm ../../mbmap/mv_Option3.bin
rm ../../mbmap/mv_Option4.bin
rm ../../mbmap/mv_Option5.bin

rm ./mbmap_NoInterpolation/mv_Option1.bin
rm ./mbmap_NoInterpolation/mv_Option2.bin
rm ./mbmap_NoInterpolation/mv_Option3.bin
rm ./mbmap_NoInterpolation/mv_Option4.bin
rm ./mbmap_NoInterpolation/mv_Option5.bin

#%%%%%%%%%% decoding the .264 files
./ldecod.exe -f decoder_CO.cfg -p InputFile="./vid/Boxing_ffmpeg_Option1.264" -p OutputFile="./vid/Boxing_ffmpeg_decoded_Options.yuv"
cp mv.bin ../../mbmap/mv_Option1_Dec.bin
mv mv.bin ../../mbmap_NoInterpolation/mv_Option1_Dec.bin

./ldecod.exe -f decoder_CO.cfg -p InputFile="./vid/Boxing_ffmpeg_Option2.264" -p OutputFile="./vid/Boxing_ffmpeg_decoded_Options.yuv"
cp mv.bin ../../mbmap/mv_Option2_Dec.bin
mv mv.bin ../../mbmap_NoInterpolation/mv_Option2_Dec.bin

./ldecod.exe -f decoder_CO.cfg -p InputFile="./vid/Boxing_ffmpeg_Option3.264" -p OutputFile="./vid/Boxing_ffmpeg_decoded_Options.yuv"
cp mv.bin ../../mbmap/mv_Option3_Dec.bin
mv mv.bin ../../mbmap_NoInterpolation/mv_Option3_Dec.bin

./ldecod.exe -f decoder_CO.cfg -p InputFile="./vid/Boxing_ffmpeg_Option4.264" -p OutputFile="./vid/Boxing_ffmpeg_decoded_Options.yuv"
cp mv.bin ../../mbmap/mv_Option4_Dec.bin
mv mv.bin ../../mbmap_NoInterpolation/mv_Option4_Dec.bin

./ldecod.exe -f decoder_CO.cfg -p InputFile="./vid/Boxing_ffmpeg_Option5.264" -p OutputFile="./vid/Boxing_ffmpeg_decoded_Options.yuv"
cp mv.bin ../../mbmap/mv_Option5_Dec.bin
mv mv.bin ../../mbmap_NoInterpolation/mv_Option5_Dec.bin

#%%%%%%%%%% deleteing old processed MV files
cd ../../mbmap
#cd ../../mbmap_NoInterpolation

rm mv_Option1.bin
rm mv_Option2.bin
rm mv_Option3.bin
rm mv_Option4.bin
rm mv_Option5.bin

#%%%%%%%%%% Extracting the MVs
./mbmap -h 240 -w 320 -o mv_Option1.bin mv_Option1_Dec.bin
./mbmap -h 240 -w 320 -o mv_Option2.bin mv_Option2_Dec.bin
./mbmap -h 240 -w 320 -o mv_Option3.bin mv_Option3_Dec.bin
./mbmap -h 240 -w 320 -o mv_Option4.bin mv_Option4_Dec.bin
./mbmap -h 240 -w 320 -o mv_Option5.bin mv_Option5_Dec.bin

#%%%%%%%%%% copying the MVs to the directory to be processed by matlab
mv ./mv_Option1.bin ../../../UCLResearch/MVX/
mv ./mv_Option2.bin ../../../UCLResearch/MVX/
mv ./mv_Option3.bin ../../../UCLResearch/MVX/
mv ./mv_Option4.bin ../../../UCLResearch/MVX/
mv ./mv_Option5.bin ../../../UCLResearch/MVX/
cd ..


