#!/bin/bash
clear

QP_List='0 4 8 12 16 20 24 28 32 36 40 44 48 51'
MVSR_List='16 32 64'
SpatialInterPolation_List='0 1'
MVResolution_List='8 16'
InputFile="box.yuv"

for MVResolution in $MVResolution_List
do
 for SpatialInterPolation in $SpatialInterPolation_List
 do 
  for MVSR in $MVSR_List
  do
   for QP in $QP_List
   do
    echo QP=$QP , Search Range=$MVSR, Spatial Interpolation=$SpatialInterPolation, MV Resolution=$MVResolution
    ./TryMe_JM_Function $QP $MVSR  $SpatialInterPolation $MVResolution $InputFile
   done
  done
 done
done
